export const categories = [
  { name: "action" },
  { name: "adventure" },
  { name: "indie" },
  { name: "rpg" },
  { name: "strategy" },
  { name: "open world" },
  { name: "shooter" },
  { name: "puzzle" },
  { name: "first person" },
  { name: "narration" },
  { name: "simulator" },
  { name: "casual" },
  { name: "turn-based" },
  { name: "exploration" },
  { name: "horror" },
  { name: "platformer" },
  { name: "party" },
  { name: "survival" },
  { name: "trivia" },
  { name: "city builder" },
  { name: "steath" },
  { name: "fighting" },
  { name: "comedy" },
  { name: "action-adventure" },
];
